config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root 'books#top'
  resources :users
 end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true,length: { maximum: 200 }
	validates :body, presence: true,length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books = Book.all
  	@book = Book.new
    @user = current_user
  end

  def show
  	@books = Book.find(params[:id])
    @book = Book.new
  end

  def top
  	@book = Book.new
  	@books = Book.all
  end

  def create
  	book = Book.new(book_params)
    book.user_id = current_user.id
  	if book.save
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(book.id)
    else
    @book = book
    @books = Book.all
    render :index
    end

  end
  def edit
  @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

  def update
  	book = Book.find(params[:id])
  	book.update(book_params)
  	if book.save
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(book.id)
    else
    @book = book
    render :edit
    end

  end

  def destroy
  	book = Book.find(params[:id])
    if book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path(@books)
    end
  end
  private
   def book_params
   	params.require(:book).permit(:title, :body)
   end

end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="main">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
			<% if @book.errors.any? %>
  				<div id="error_explanation" class="alert alert-danger">
  					<ul>
  						<% @book.errors.full_messages.each do |message| %>
  						<li>error</li>
  						<li><%= message %></li>
  						<% end %>
  					</ul>
  				</div>
  			<% end %>

			<%= form_for(@book) do |f| %>
    			<label>Title</label><br>
    			<%= f.text_field :title, class: "col-xs-12" %>
    			<label>Opinion</label><br>
    			<%= f.text_area :body, class: "col-xs-12" %>
				<div class="actions">
    			<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
    			</div><br>
			<%= link_to "Show", book_path(@book.id) %>|<%= link_to "Back", books_path(@books) %>
			<% end %>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  <div class="row">
  <div class="main">
    
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>

      <% @book.errors.full_messages.each do |message| %>
        <li>error</li>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 <div class="col-xs-3">
    <%= render 'layouts/sidebar', user: current_user, book: @book %>
  </div>
 <div class="col-xs-9">


  <h1>Books</h1>
  <table  class="table table-striped">
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody>
    <tr>
      <td><a href="<%= user_path(book.user) %>"><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></a></td>
      <td><%=link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>

    </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>
 </div>

</div>

app/views/books/show.html.erb
<div class="container">
      <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

  <% if @book.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
    	<ul>
    		<% @book.errors.full_messages.each do |message| %>
        		<li><%= message %></li>
        <% end %>
      </ul>
	</div>
	<% end %>
  <div class="row">
  <div class="main">
    <div class="col-xs-3">
      <%= flash[:notice] %>
      <h2>User info</h2>
        <div class="profile-container row">
          <%= attachment_image_tag @books.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= @books.user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @books.user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <% if @books.user == current_user %>
          <div class="row">
            <%= link_to "", edit_user_path(current_user), class: "glyphicon glyphicon-wrench col-xs-12 btn btn-default" %>
          </div>
          <% else %>
          <%= link_to "", user_path(current_user), class: "glyphicon glyphicon-wrench col-xs-12 btn btn-default" %>
          <% end %>
        </div>
        <h2>New book</h2>
        <%= form_for(@book) do |f| %>
          <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "col-xs-12" %>
          </div>
            <div class="field row">
              <label>Opinion</label>
              <%= f.text_area :body, class: "col-xs-12" %>
            </div>
              <div class="action row">
                <%=f.submit class: "btn btn-primary col-xs-12"%>
              </div>
        <% end %>
    </div>
    <div class="col-xs-9">
      <div class="row">
			<h1>Book detail</h1>
			<table class="table table-striped">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
              <a href="<%= user_path(@books.user) %>">
							 <%= attachment_image_tag @books.user, :profile_image, :fill, 20, 20, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
							 <br><%= @books.user.name %></a>
						</td>
						<td><%= @books.title %></td>
						<td><%= @books.body %></td>
						<% if @books.user == current_user %>
						<td><button class="btn-sm btn-success"><%= link_to "Edit", edit_book_path(@books) %></td></button>
						<td>
							<button class="btn-sm btn-danger"><%= link_to "Destroy", book_path(@books), method: :delete, "data-confirm" => "Are you sure？" %></button>
						</td>
						<% end %>
					</tr>
				</tbody>
			</table>
     </div>
		</div>
  </div>
	</div>
</div>

app/views/books/top.html.erb
<body>
  <div class="main">
    <nav class="nav navbar-nav navbar-left">
    </nav>

<div class="container">
        <div class="flash">
        <%= flash[:notice] %>
      </div>
	<div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

<div class="btn-wrapper">
<div class ="row">
	<a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a>
</div>
<div class ="row">
<a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="<%=new_user_registration_path %>">Sign Up</a>
</div>
</div>
</div>
</div>
</div>
</body>
</html>